#!/bin/bash

if pkg-missing "$@"; then
  yay -S --noconfirm --needed "$@" || exit 1
fi

for pkg in "$@"; do
  # Secondary check to handle states where yay doesn't actually register an error
  if ! yay -Q "$pkg" &>/dev/null; then
    echo -e "\033[31mError: Package '$pkg' did not install\033[0m" >&2
    exit 1
  fi
done

exit 0
